# Generated by Django 5.1.6 on 2025-03-01 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentPlaybook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('malware', 'Malware'), ('phishing', 'Phishing'), ('ddos', 'DDoS'), ('databreach', 'Data Breach')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('affected_systems', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('playbook_text', models.TextField(blank=True)),
            ],
        ),
    ]
