# Generated by Django 5.1.6 on 2025-03-02 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('applicable_incidents', models.CharField(choices=[('malware', 'Malware'), ('phishing', 'Phishing'), ('ddos', 'DDoS'), ('databreach', 'Data Breach')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PlaybookTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('incident_type', models.CharField(choices=[('malware', 'Malware'), ('phishing', 'Phishing'), ('ddos', 'DDoS'), ('databreach', 'Data Breach')], max_length=20)),
                ('template_text', models.TextField()),
                ('created_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='incidentplaybook',
            name='incident_detected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentplaybook',
            name='incident_fixed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentplaybook',
            name='workflow',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='CustomStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_description', models.TextField()),
                ('step_order', models.IntegerField(default=0)),
                ('playbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_steps', to='generator.incidentplaybook')),
            ],
        ),
        migrations.CreateModel(
            name='DecisionPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=200)),
                ('action', models.TextField()),
                ('playbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_points', to='generator.incidentplaybook')),
            ],
        ),
    ]
